// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CATAPULTE_H
#define CATAPULTE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Catapulte: public Subsystem {
private:

	std::shared_ptr<SpeedController> monte;
	std::shared_ptr<AnalogPotentiometer> pot;

	bool m_reaching;
	bool m_isGoingUp;
	double m_setpoint;

public:

	static double potMax;
	static double potMin;
	static double potShoot;

	Catapulte();
	void InitDefaultCommand();
	void SetAtShoot();
	void SetAtMin();
	void Reach();
	void StopMonte();
	void Up();
	void Down();
	void Maintien();
	bool HasReached();


	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
