// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Catapulte.h"
#include "../RobotMap.h"


double Catapulte::potMax(0);
double Catapulte::potMin(0);
double Catapulte::potShoot(0);

Catapulte::Catapulte() : Subsystem("Catapulte") {

    monte = RobotMap::catapulteMonte;

    m_reaching = false;
    m_isGoingUp = false;
    m_setpoint = 0;

}

void Catapulte::InitDefaultCommand() {

}

void Catapulte::SetAtShoot() {
   	m_setpoint = potShoot;
}

void Catapulte::SetAtMin() {
	m_setpoint = potMax;
}

void Catapulte::Reach() {

	if(!HasReached()) {

		m_reaching = true;

		if (pot->Get() < m_setpoint){
			Down();
			m_isGoingUp = false;
		}
		else  {
			Up();
			m_isGoingUp = true;
		}
	}
	else {
		Maintien();
	}
}


void Catapulte::Up() {

	if (pot->Get() >= potMin) {
		monte->Set(0.4);
	}
	else  {
		StopMonte();
	}
}

void Catapulte::Down() {
	if (pot->Get() <= potMax) {
		monte->Set(-0.1);
	}
	else  {
		StopMonte();
	}
}

void Catapulte::StopMonte() {
	monte->Set(0);
	m_reaching = false;
}

void Catapulte::Maintien() {
	if(pot->Get() > potMin)
		monte->Set(0.1);
}

bool Catapulte::HasReached() {
	if (m_reaching) {

		bool doneReaching;
		doneReaching = (m_isGoingUp == (pot->Get() <= m_setpoint));

		if (doneReaching)
			m_reaching = false;

		return doneReaching;
	}

	else {
		return (pot->Get() < m_setpoint + 0.004) && (pot->Get() > m_setpoint - 0.004);
	}

}
