// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "RouesPivot.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

RouesPivot::RouesPivot() : Subsystem("RouesPivot") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    pistonGauche = RobotMap::rouesPivotpistonGauche;
    pistonDroit = RobotMap::rouesPivotpistonDroit;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void RouesPivot::InitDefaultCommand() {

}

void RouesPivot::PistonGaucheExtend() {
	pistonGauche->Set(DoubleSolenoid::kReverse);
}

void RouesPivot::PistonGaucheRetract() {
	pistonGauche->Set(DoubleSolenoid::kForward);
}

void RouesPivot::PistonGaucheOff() {
	pistonGauche->Set(DoubleSolenoid::kOff);
}

void RouesPivot::PistonDroitExtend() {
	pistonDroit->Set(DoubleSolenoid::kReverse);
}

void RouesPivot::PistonDroitRetract() {
	pistonDroit->Set(DoubleSolenoid::kForward);
}

void RouesPivot::PistonDroitOff() {
	pistonDroit->Set(DoubleSolenoid::kOff);
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

