// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Avancer.h"
#include "Autonomous.h"
#include "Tourner.h"
#include "Viser.h"
#include "BSetBas.h"
#include "PMonte.h"
#include "CSetShoot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Autonomous::Autonomous() {

    AddSequential(new BSetBas());
	AddSequential(new Avancer(4.5));
	AddSequential(new Tourner(40));
	AddSequential(new PMonte());
	AddSequential(new CSetShoot());
	AddSequential(new Viser());

 }
