// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CLoad.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CLoad::CLoad(): Command("CLoad") {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void CLoad::Initialize() {
	SetTimeout(5);
}

// Called repeatedly when this Command is scheduled to run
void CLoad::Execute() {
	Robot::shooter->ConvToBack();
	Robot::shooter->SpinToBack();
}

// Make this return true when this Command no longer needs to run execute()
bool CLoad::IsFinished() {
    return Robot::shooter->IsLoaded() || IsTimedOut();
}

// Called once after isFinished returns true
void CLoad::End() {
	  DriverStation::ReportError("Fin Cload");
	Robot::shooter->StopConv();
	Robot::shooter->StopSpin();

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CLoad::Interrupted() {
	End();
}
