// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CSpin.h"
#include "CShoot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

CSpin::CSpin(bool shoot): Command("CSpin") {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_shoot = shoot;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void CSpin::Initialize() {
	SetTimeout(1.0);
	Robot::shooter->Spin();
	DriverStation::ReportError("Spin!");
}

// Called repeatedly when this Command is scheduled to run
void CSpin::Execute() {
	//Robot::shooter->Spin();

}

// Make this return true when this Command no longer needs to run execute()
bool CSpin::IsFinished() {
    return IsTimedOut();
}

// Called once after isFinished returns true
void CSpin::End() {
	if(m_shoot)
		Scheduler::GetInstance()->AddCommand(new CShoot());
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CSpin::Interrupted() {

}
