// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:

	std::shared_ptr<Joystick> stick;
	std::shared_ptr<Joystick> gamepad;


	std::shared_ptr<JoystickButton> button1;
	std::shared_ptr<JoystickButton> button2;
	std::shared_ptr<JoystickButton> button3;
	std::shared_ptr<JoystickButton> button4;
	std::shared_ptr<JoystickButton> button9;
	std::shared_ptr<JoystickButton> button10;
	std::shared_ptr<JoystickButton> button11;
	std::shared_ptr<JoystickButton> button12;

	std::shared_ptr<JoystickButton> buttonG1;
	std::shared_ptr<JoystickButton> buttonG2;
	std::shared_ptr<JoystickButton> buttonG3;
	std::shared_ptr<JoystickButton> buttonG4;
	std::shared_ptr<JoystickButton> buttonG6;
	std::shared_ptr<JoystickButton> buttonG7;
	std::shared_ptr<JoystickButton> buttonG8;

public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<Joystick> getStick();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
